# Generated by Django 3.0.5 on 2024-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
